name = "DataGraphPlots"
uuid = "edc0d1de-cbb6-43e5-80c3-282b59182d08"
authors = ["dlcole3 <dlcole3@wisc.edu> and contributors"]
version = "0.1.0"

[deps]
DataGraphs = "61570925-d2eb-4b32-b37d-b99a9c94b618"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DataGraphs = "0.1.0"
GeometryBasics = "0.4.3"
GLMakie = "^0.8.2"
GraphMakie = "^0.5.3"
Graphs = "1.7.2"
julia = "^1.7.0"
LayeredLayouts = "0.2.5"
Makie = "0.19.2"
NetworkLayout = "0.4.4"
Plots = "1.33.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
